export BATCHHOME=~/batch;
export BATCH_FILE_PATH=$BATCHHOME/file;
export SHARE_FILE_PATH=/shareDir/settlefile;
export B_LOG_FILE_PATH=$BATCHHOME/log;
FL_PATH=$BATCHHOME/file;export FL_PATH
FILEDIR=$BATCH_FILE_PATH/;export FILEDIR;
PATH=./:$BATCHHOME/bin:$BATCHHOME/sbin:/sbin:/bin:/usr/sbin:/usr/bin:$PATH;export PATH
LD_LIBRARY_PATH=$BATCHHOME/lib:$ORACLE_HOME/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
LIBPATH=$LD_LIBRARY_PATH; export LIBPATH

LOG_MODE=5;export LOG_MODE;
LOG_SWITCH_MODE=0;export LOG_SWITCH_MODE;
LOG_SIZE=1024;export LOG_SIZE;

export CUP_ID=05780000

FL_FLAG_PAN=N;export FL_FLAG_PAN
FL_FLAG_AMT=Y;export FL_FLAG_AMT


SETT_BAND_NO=309391000011;export SETT_BAND_NO
