#!/bin/sh
###############################################################################
##  Copyright 2012, Shanghai Huateng Software Systems Co., Ltd.
##  All right reserved.
##
##  THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF SHANGHAI HUATENG
##  SOFTWARE SYSTEMS CO., LTD.  THE CONTENTS OF THIS FILE MAY NOT
##  BE DISCLOSED TO THIRD PARTIES, COPIED OR DUPLICATED IN ANY FORM,
##  IN WHOLE OR IN PART, WITHOUT THE PRIOR WRITTEN PERMISSION OF
##  SHANGHAI HUATENG SOFTWARE SYSTEMS CO., LTD.
##
##  脚 本 名: runbatch
##  功    能: 清结算系统启动
##  编程人员: 
##  开发时间: 
##  备    注:
################################################################################

InstMisn & 
MMisnMain & 
MSubMisnMain &
TMisnMain &
TSubMisnMain &


