#!/bin/sh
. $HOME/.bash_profile

#kill server
stopbatch >/dev/null  2>&1 
sleep 1
#系统当前日期
CURDATE=`date +%Y%m%d`
echo "系统当前日期: ${CURDATE}"

#取日期参数
if [ $# -gt 0 ]
then
    DATE=$1
else
    DATE=`date +%Y%m%d`
fi
echo "参数日期: ${DATE}"

#取日期参数
#if [ $# -gt 0 ]
#then
#    NEXTDATE=$2
#else
#    NEXTDATE=`date +%Y%m%d`
#fi
#echo "参数日期: ${SYSSTERDATE}"

#启动服务前，清理当前日期及以后的tbl_child_inf、tbl_proc_ctl、tbl_mission_inf表数据
echo "start delete database................."
sqlplus $DBUSER/$DBPWD@$DBNAME << EOF
update HT_TBL_DATE_INF set stoday = ${DATE},stwodaysago=`date -d"2 day ago ${DATE}" +%Y%m%d`, syesterday = `date -d"yesterday ${DATE}" +%Y%m%d`,snextdate=`date -d"-1 day ago ${DATE}" +%Y%m%d`;
delete from HT_TBL_MISSION_inf where SETTLMT_DATE = ${DATE};
delete from ht_tbl_child_inf where SETTLMT_DATE = ${DATE};
update ht_tbl_child_time t set t.child_status='0',t.child_finish_point='0',t.child_err_point='0' where t.mission_date=${DATE};

update HT_TBL_ACCT_RSLT set acct_statu='N' where  ACCT_DATE = ${DATE};
delete from ht_tbl_sett_list where SETT_DATE = ${DATE};

delete from HT_TBL_HOST_TXN where SETT_DATE = ${DATE};
delete from HT_TBL_GATEWAY_TXN where SETT_DATE = ${DATE};
delete from HT_TBL_wift_TXN where SETT_DATE = ${DATE};
delete from HT_TBL_ACTIVE_MCHT_INF where SETT_DATE = ${DATE};
delete from HT_TBL_CIB_TXN where SETT_DATE = ${DATE};
delete from HT_TBL_ALIPAY_TXN where SETT_DATE = ${DATE};
delete from HT_TBL_WECHAT_TXN where SETT_DATE = ${DATE};
delete from HT_TBL_ERR_FLOW where SETT_DATE = ${DATE};
delete from HT_TBL_CMP_FLOW where SETT_DATE = ${DATE};
delete from HT_TBL_DAT_FLOW where SETT_DATE = ${DATE};
delete from HT_TBL_SETT_FLOW where SETT_DATE = ${DATE};
delete from HT_TBL_SETT_RSLT where SETT_DATE = ${DATE};
delete from HT_TBL_ACCT_RSLT where SETT_DATE = ${DATE};
delete from HT_TBL_FILE_INFO@PUBLIC_DAT where  SETT_DATE = ${DATE};
commit;
EOF
echo "finish delete database................."
#
#runbatch

sleep 2
