all:
	make -f Task_0100.mak
	make -f Task_0101.mak
	make -f Task_0102.mak
	make -f Task_0103.mak
	make -f Task_0104.mak
	make -f Task_0105.mak
	make -f Task_0106.mak
	make -f Task_0116.mak
	make -f Task_0130.mak
	make -f Task_0401.mak
	make -f Task_0402.mak
	make -f Task_0403.mak
	make -f Task_0404.mak
	make -f Task_0405.mak
	make -f Task_0406.mak
	make -f Task_0407.mak
	make -f Task_0408.mak
	make -f Task_0421.mak
	make -f Task_0701.mak
	make -f Task_0702.mak
	make -f Task_0703.mak
	make -f Task_0802.mak
	make -f Task_0803.mak
	make -f Task_0901.mak
	make -f Task_2201.mak
	make -f Task_4101.mak
	make -f Task_5101.mak
	make -f Task_5500.mak
	make -f Task_5501.mak
	make -f Task_5502.mak
	make -f Task_6101.mak
	make -f Task_6102.mak
	make -f Task_6202.mak
	make -f Task_6501.mak
	make -f Task_6601.mak
	make -f Task_6602.mak
	make -f Task_6800.mak
	make -f Task_7100.mak
	make -f Task_7101.mak
	make -f Task_7102.mak
	make -f Task_7111.mak
	make -f Task_7201.mak
	make -f Task_7202.mak
	make -f Task_7222.mak
	make -f Task_7301.mak
	make -f Task_7302.mak
	make -f Task_7400.mak
	make -f Task_7401.mak
	make -f Task_7402.mak
	make -f Task_7502.mak
	make -f Task_7802.mak
	make -f Task_7822.mak
	make -f Task_7902.mak
	make -f Task_8002.mak
	make -f Task_8102.mak
	make -f Task_8701.mak
	#make -f Task_8702.mak
	make -f Task_9901.mak	

	make -f Task_9029.mak
	make -f Task_9030.mak
	make -f Task_9003.mak
	make -f Task_9004.mak
	make -f Task_9005.mak
	make -f Task_9006.mak
	make -f Task_0109.mak
	make -f Task_0409.mak
	make -f Task_0700.mak
	make -f Task_0800.mak
	make -f Task_9007.mak

	make -f Task_7103.mak
	make -f Task_7403.mak
	make -f Task_8703.mak
	make -f Task_6502.mak
	make -f Task_6603.mak
clean debug release:
	make -f Task_0100.mak $@
	make -f Task_0101.mak $@
	make -f Task_0102.mak $@
	make -f Task_0103.mak $@
	make -f Task_0104.mak $@
	make -f Task_0105.mak $@
	make -f Task_0106.mak $@
	make -f Task_0116.mak $@
	make -f Task_0130.mak $@
	make -f Task_0401.mak $@
	make -f Task_0402.mak $@
	make -f Task_0403.mak $@
	make -f Task_0404.mak $@
	make -f Task_0405.mak $@
	make -f Task_0406.mak $@
	make -f Task_0407.mak $@
	make -f Task_0408.mak $@
	make -f Task_0421.mak $@
	make -f Task_0701.mak $@
	make -f Task_0702.mak $@
	make -f Task_0703.mak $@
	make -f Task_0802.mak $@
	make -f Task_0803.mak $@
	make -f Task_0901.mak $@
	make -f Task_2201.mak $@
	make -f Task_4101.mak $@
	make -f Task_5101.mak $@
	make -f Task_5500.mak $@
	make -f Task_5501.mak $@
	make -f Task_5502.mak $@
	make -f Task_6101.mak $@
	make -f Task_6102.mak $@
	make -f Task_6202.mak $@
	make -f Task_6501.mak $@
	make -f Task_6601.mak $@
	make -f Task_6602.mak $@
	make -f Task_6800.mak $@
	make -f Task_7100.mak $@
	make -f Task_7101.mak $@
	make -f Task_7102.mak $@
	make -f Task_7111.mak $@
	make -f Task_7201.mak $@
	make -f Task_7202.mak $@
	make -f Task_7222.mak $@
	make -f Task_7301.mak $@
	make -f Task_7302.mak $@
	make -f Task_7400.mak $@
	make -f Task_7401.mak $@
	make -f Task_7402.mak $@
	make -f Task_7502.mak $@
	make -f Task_7802.mak $@
	make -f Task_7822.mak $@
	make -f Task_7902.mak $@
	make -f Task_8002.mak $@
	make -f Task_8102.mak $@
	make -f Task_8701.mak $@
	#make -f Task_8702.mak $@
	make -f Task_9901.mak $@	

	make -f Task_9029.mak $@
	make -f Task_9030.mak $@
	make -f Task_9003.mak $@
	make -f Task_9004.mak $@
	make -f Task_9005.mak $@
	make -f Task_9006.mak $@

	make -f Task_0109.mak $@
	make -f Task_0409.mak $@
	make -f Task_0700.mak $@
	make -f Task_0800.mak $@
	make -f Task_9007.mak $@

	make -f Task_7103.mak $@
	make -f Task_7403.mak $@
	make -f Task_8703.mak $@
	make -f Task_6502.mak $@
	make -f Task_6603.mak $@
